/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from './app-routing.module';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/core/src/application_init';
import * as import9 from '@angular/core/src/testability/testability';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '@angular/core/src/linker/compiler';
import * as import12 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import13 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import14 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import15 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import16 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import17 from '@angular/core/src/animation/animation_queue';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/platform-browser/src/browser/title';
import * as import20 from '@angular/common/src/location/location';
import * as import21 from '@angular/router/src/url_tree';
import * as import22 from '@angular/router/src/router_outlet_map';
import * as import23 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import24 from '@angular/router/src/router_preloader';
import * as import25 from '@angular/core/src/di/injector';
import * as import26 from '../components/daily-reading.component.ngfactory';
import * as import27 from '../components/clow-card-detail.component.ngfactory';
import * as import28 from '../components/app.component.ngfactory';
import * as import29 from '@angular/core/src/i18n/tokens';
import * as import30 from '@angular/core/src/application_tokens';
import * as import31 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import32 from '@angular/platform-browser/src/dom/events/key_events';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import35 from '@angular/common/src/location/platform_location';
import * as import36 from '../components/daily-reading.component';
import * as import37 from '../components/clow-card-detail.component';
import * as import38 from '@angular/router/src/url_handling_strategy';
import * as import39 from '@angular/router/src/route_reuse_strategy';
import * as import40 from '@angular/router/src/router';
import * as import41 from '@angular/core/src/console';
import * as import42 from '@angular/core/src/error_handler';
import * as import43 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import44 from '@angular/platform-browser/src/dom/animation_driver';
import * as import45 from '@angular/core/src/render/api';
import * as import46 from '@angular/core/src/security';
import * as import47 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import48 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import49 from '@angular/common/src/location/location_strategy';
import * as import50 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import51 from '@angular/router/src/router_config_loader';
import * as import52 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _ROUTER_FORROOT_GUARD_3:any;
  _RouterModule_4:import5.RouterModule;
  _AppRoutingModule_5:import6.AppRoutingModule;
  _AppModule_6:import1.AppModule;
  __LOCALE_ID_7:any;
  __NgLocalization_8:import7.NgLocaleLocalization;
  _ErrorHandler_9:any;
  _RouterInitializer_10:import5.RouterInitializer;
  _APP_INITIALIZER_11:any[];
  _ApplicationInitStatus_12:import8.ApplicationInitStatus;
  _Testability_13:import9.Testability;
  _ApplicationRef__14:import10.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import11.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import12.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import13.EventManager;
  _DomSharedStylesHost_22:import14.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import15.DomRootRenderer_;
  __NgProbeToken_25:any[];
  __RootRenderer_26:any;
  __DomSanitizer_27:import16.DomSanitizerImpl;
  __Sanitizer_28:any;
  __AnimationQueue_29:import17.AnimationQueue;
  __ViewUtils_30:import18.ViewUtils;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __SharedStylesHost_33:any;
  __Title_34:import19.Title;
  __APP_BASE_HREF_35:any;
  __ROUTER_CONFIGURATION_36:any;
  __LocationStrategy_37:any;
  __Location_38:import20.Location;
  __UrlSerializer_39:import21.DefaultUrlSerializer;
  __RouterOutletMap_40:import22.RouterOutletMap;
  __NgModuleFactoryLoader_41:import23.SystemJsNgModuleLoader;
  __ROUTES_42:any[];
  __Router_43:any;
  __ActivatedRoute_44:any;
  _NoPreloading_45:import24.NoPreloading;
  _PreloadingStrategy_46:any;
  _RouterPreloader_47:import24.RouterPreloader;
  __PreloadAllModules_48:import24.PreloadAllModules;
  __ROUTER_INITIALIZER_49:any;
  __APP_BOOTSTRAP_LISTENER_50:any[];
  constructor(parent:import25.Injector) {
    super(parent,[
      import26.DailyReadingComponentNgFactory,
      import27.ClowCardDetailComponentNgFactory,
      import28.AppComponentNgFactory
    ]
    ,[import28.AppComponentNgFactory]);
  }
  get _LOCALE_ID_7():any {
    if ((this.__LOCALE_ID_7 == null)) { (this.__LOCALE_ID_7 = import3._localeFactory(this.parent.get(import29.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_7;
  }
  get _NgLocalization_8():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_8 == null)) { (this.__NgLocalization_8 = new import7.NgLocaleLocalization(this._LOCALE_ID_7)); }
    return this.__NgLocalization_8;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == null)) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import11.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import11.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import30._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == null)) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import12.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == null)) { (this.__HAMMER_GESTURE_CONFIG_19 = new import12.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == null)) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import31.DomEventsPlugin(),
      new import32.KeyEventsPlugin(),
      new import12.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import13.EventManager {
    if ((this.__EventManager_21 == null)) { (this.__EventManager_21 = new import13.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import33.NgZone))); }
    return this.__EventManager_21;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == null)) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import15.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == null)) { (this.__DomRootRenderer_24 = new import15.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23,this._APP_ID_17)); }
    return this.__DomRootRenderer_24;
  }
  get _NgProbeToken_25():any[] {
    if ((this.__NgProbeToken_25 == null)) { (this.__NgProbeToken_25 = [import5.routerNgProbeToken()]); }
    return this.__NgProbeToken_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == null)) { (this.__RootRenderer_26 = import34._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import34.NgProbeToken,(null as any)),this._NgProbeToken_25)); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import16.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == null)) { (this.__DomSanitizer_27 = new import16.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == null)) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _AnimationQueue_29():import17.AnimationQueue {
    if ((this.__AnimationQueue_29 == null)) { (this.__AnimationQueue_29 = new import17.AnimationQueue(this.parent.get(import33.NgZone))); }
    return this.__AnimationQueue_29;
  }
  get _ViewUtils_30():import18.ViewUtils {
    if ((this.__ViewUtils_30 == null)) { (this.__ViewUtils_30 = new import18.ViewUtils(this._RootRenderer_26,this._Sanitizer_28,this._AnimationQueue_29)); }
    return this.__ViewUtils_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == null)) { (this.__IterableDiffers_31 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == null)) { (this.__KeyValueDiffers_32 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_32;
  }
  get _SharedStylesHost_33():any {
    if ((this.__SharedStylesHost_33 == null)) { (this.__SharedStylesHost_33 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_33;
  }
  get _Title_34():import19.Title {
    if ((this.__Title_34 == null)) { (this.__Title_34 = new import19.Title()); }
    return this.__Title_34;
  }
  get _APP_BASE_HREF_35():any {
    if ((this.__APP_BASE_HREF_35 == null)) { (this.__APP_BASE_HREF_35 = '/'); }
    return this.__APP_BASE_HREF_35;
  }
  get _ROUTER_CONFIGURATION_36():any {
    if ((this.__ROUTER_CONFIGURATION_36 == null)) { (this.__ROUTER_CONFIGURATION_36 = {}); }
    return this.__ROUTER_CONFIGURATION_36;
  }
  get _LocationStrategy_37():any {
    if ((this.__LocationStrategy_37 == null)) { (this.__LocationStrategy_37 = import5.provideLocationStrategy(this.parent.get(import35.PlatformLocation),this._APP_BASE_HREF_35,this._ROUTER_CONFIGURATION_36)); }
    return this.__LocationStrategy_37;
  }
  get _Location_38():import20.Location {
    if ((this.__Location_38 == null)) { (this.__Location_38 = new import20.Location(this._LocationStrategy_37)); }
    return this.__Location_38;
  }
  get _UrlSerializer_39():import21.DefaultUrlSerializer {
    if ((this.__UrlSerializer_39 == null)) { (this.__UrlSerializer_39 = new import21.DefaultUrlSerializer()); }
    return this.__UrlSerializer_39;
  }
  get _RouterOutletMap_40():import22.RouterOutletMap {
    if ((this.__RouterOutletMap_40 == null)) { (this.__RouterOutletMap_40 = new import22.RouterOutletMap()); }
    return this.__RouterOutletMap_40;
  }
  get _NgModuleFactoryLoader_41():import23.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_41 == null)) { (this.__NgModuleFactoryLoader_41 = new import23.SystemJsNgModuleLoader(this._Compiler_16,this.parent.get(import23.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_41;
  }
  get _ROUTES_42():any[] {
      if ((this.__ROUTES_42 == null)) { (this.__ROUTES_42 = [[
        {
          path: '',
          redirectTo: '/daily-reading',
          pathMatch: 'full'
        }
        ,
        {
          path: 'daily-reading',
          component: import36.DailyReadingComponent
        }
        ,
        {
          path: 'clow-card/:id',
          component: import37.ClowCardDetailComponent
        }

      ]
    ]); }
    return this.__ROUTES_42;
  }
  get _Router_43():any {
    if ((this.__Router_43 == null)) { (this.__Router_43 = import5.setupRouter(this._ApplicationRef_15,this._UrlSerializer_39,this._RouterOutletMap_40,this._Location_38,this,this._NgModuleFactoryLoader_41,this._Compiler_16,this._ROUTES_42,this._ROUTER_CONFIGURATION_36,this.parent.get(import38.UrlHandlingStrategy,(null as any)),this.parent.get(import39.RouteReuseStrategy,(null as any)))); }
    return this.__Router_43;
  }
  get _ActivatedRoute_44():any {
    if ((this.__ActivatedRoute_44 == null)) { (this.__ActivatedRoute_44 = import5.rootRoute(this._Router_43)); }
    return this.__ActivatedRoute_44;
  }
  get _PreloadAllModules_48():import24.PreloadAllModules {
    if ((this.__PreloadAllModules_48 == null)) { (this.__PreloadAllModules_48 = new import24.PreloadAllModules()); }
    return this.__PreloadAllModules_48;
  }
  get _ROUTER_INITIALIZER_49():any {
    if ((this.__ROUTER_INITIALIZER_49 == null)) { (this.__ROUTER_INITIALIZER_49 = import5.getBootstrapListener(this._RouterInitializer_10)); }
    return this.__ROUTER_INITIALIZER_49;
  }
  get _APP_BOOTSTRAP_LISTENER_50():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_50 == null)) { (this.__APP_BOOTSTRAP_LISTENER_50 = [this._ROUTER_INITIALIZER_49]); }
    return this.__APP_BOOTSTRAP_LISTENER_50;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ROUTER_FORROOT_GUARD_3 = import5.provideForRootGuard(this.parent.get(import40.Router,(null as any)));
    this._RouterModule_4 = new import5.RouterModule(this._ROUTER_FORROOT_GUARD_3);
    this._AppRoutingModule_5 = new import6.AppRoutingModule();
    this._AppModule_6 = new import1.AppModule();
    this._ErrorHandler_9 = import4.errorHandler();
    this._RouterInitializer_10 = new import5.RouterInitializer(this);
    this._APP_INITIALIZER_11 = [import5.getAppInitializer(this._RouterInitializer_10)];
    this._ApplicationInitStatus_12 = new import8.ApplicationInitStatus(this._APP_INITIALIZER_11);
    this._Testability_13 = new import9.Testability(this.parent.get(import33.NgZone));
    this._ApplicationRef__14 = new import10.ApplicationRef_(this.parent.get(import33.NgZone),this.parent.get(import41.Console),this,this._ErrorHandler_9,this,this._ApplicationInitStatus_12,this.parent.get(import9.TestabilityRegistry,(null as any)),this._Testability_13);
    this._DomSharedStylesHost_22 = new import14.DomSharedStylesHost(this._DOCUMENT_18);
    this._NoPreloading_45 = new import24.NoPreloading();
    this._PreloadingStrategy_46 = this._NoPreloading_45;
    this._RouterPreloader_47 = new import24.RouterPreloader(this._Router_43,this._NgModuleFactoryLoader_41,this._Compiler_16,this,this._PreloadingStrategy_46);
    return this._AppModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_3; }
    if ((token === import5.RouterModule)) { return this._RouterModule_4; }
    if ((token === import6.AppRoutingModule)) { return this._AppRoutingModule_5; }
    if ((token === import1.AppModule)) { return this._AppModule_6; }
    if ((token === import29.LOCALE_ID)) { return this._LOCALE_ID_7; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_8; }
    if ((token === import42.ErrorHandler)) { return this._ErrorHandler_9; }
    if ((token === import5.RouterInitializer)) { return this._RouterInitializer_10; }
    if ((token === import8.APP_INITIALIZER)) { return this._APP_INITIALIZER_11; }
    if ((token === import8.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import9.Testability)) { return this._Testability_13; }
    if ((token === import10.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import10.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import11.Compiler)) { return this._Compiler_16; }
    if ((token === import30.APP_ID)) { return this._APP_ID_17; }
    if ((token === import43.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import12.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import13.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import13.EventManager)) { return this._EventManager_21; }
    if ((token === import14.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import44.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import15.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import10.NgProbeToken)) { return this._NgProbeToken_25; }
    if ((token === import45.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import16.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import46.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import17.AnimationQueue)) { return this._AnimationQueue_29; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_30; }
    if ((token === import47.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import48.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import14.SharedStylesHost)) { return this._SharedStylesHost_33; }
    if ((token === import19.Title)) { return this._Title_34; }
    if ((token === import49.APP_BASE_HREF)) { return this._APP_BASE_HREF_35; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_36; }
    if ((token === import49.LocationStrategy)) { return this._LocationStrategy_37; }
    if ((token === import20.Location)) { return this._Location_38; }
    if ((token === import21.UrlSerializer)) { return this._UrlSerializer_39; }
    if ((token === import22.RouterOutletMap)) { return this._RouterOutletMap_40; }
    if ((token === import50.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_41; }
    if ((token === import51.ROUTES)) { return this._ROUTES_42; }
    if ((token === import40.Router)) { return this._Router_43; }
    if ((token === import52.ActivatedRoute)) { return this._ActivatedRoute_44; }
    if ((token === import24.NoPreloading)) { return this._NoPreloading_45; }
    if ((token === import24.PreloadingStrategy)) { return this._PreloadingStrategy_46; }
    if ((token === import24.RouterPreloader)) { return this._RouterPreloader_47; }
    if ((token === import24.PreloadAllModules)) { return this._PreloadAllModules_48; }
    if ((token === import5.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_49; }
    if ((token === import30.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_50; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
    this._DomSharedStylesHost_22.ngOnDestroy();
    this._RouterPreloader_47.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);