/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.clow-card.deck[_ngcontent-%COMP%] {\n  position: absolute;\n  left: 0px;\n  top: 0;\n  right: 0;\n  -webkit-filter: grayscale(30%); \n  filter: grayscale(30%);\n  border-radius: 8px;\n}\n\n.clow-card.deck[_ngcontent-%COMP%]:hover {\n  margin-top: -30px;\n  -webkit-box-shadow: 10px 10px 52px -14px rgba(0,0,0,0.75);\n  -moz-box-shadow: 10px 10px 52px -14px rgba(0,0,0,0.75);\n  box-shadow: 10px 10px 52px -14px rgba(0,0,0,0.75);\n  -webkit-filter: grayscale(0%); \n  filter: grayscale(0%);\n}\n\n.clow-card-desc[_ngcontent-%COMP%] {\n  position: absolute;\n  top: 800px;\n}\n\ndiv.wrapper[_ngcontent-%COMP%] {\n  margin-top: 70px;\n  position: relative;\n}'];